### ISSUE TITLE
Create Device Alias fails

### ISSUE THREAD

**Issue by fvandonk** [Cisco-SAN/mdssdk#25]
I am able to query the device aliases but when I test the create device alias example:
# Adding new device alias
new = {"device1": "21:00:00:0e:1e:30:34:a5", "device2": "21:00:00:0e:1e:30:3c:c5"}
d.create(new)

I get the following error:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\mdssdk\devicealias.py", line 230, in create
    out = self.__swobj.config(cmd)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\mdssdk\switch.py", line 1024, in config
    raise CLIError(command, error)
mdssdk.connection_manager.errors.CLIError: The command " device-alias database ;  device-alias name device1 pwwn 21:00:00:0e:1e:30:34:a5 ; " gave the error " MDS-A(config-device-alias-db)#
end MDS-A# ".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Python_Projects\MDSswitch\mds-switch.py", line 65, in <module>
    d.create(new)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\mdssdk\devicealias.py", line 232, in create
    self.__clear_lock_if_distribute()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\mdssdk\devicealias.py", line 396, in __clear_lock_if_distribute
    self.clear_lock()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\mdssdk\devicealias.py", line 308, in clear_lock
    self.__swobj.config(cmd)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\mdssdk\switch.py", line 1024, in config
    raise CLIError(command, error)
mdssdk.connection_manager.errors.CLIError: The command " terminal dont-ask ; device-alias database ; clear device-alias session ; no terminal dont-ask " gave the error " MDS-A(config-device-alias-db)#  end MDS-A# ".
PS D:\Python_Projects\MDSswitch>

**Comment by srbharadwaj** [comment]
Can you please share more details
which mdssdk version you are using , what is the switch model, switch version ,  `show running-config all | section device-alias`

**Comment by fvandonk** [comment]
mdssdk version: I ran "pip install mdssdk" yesterday which install the latests so that would be 1.5 I assume.
Switch model: 9148S
Switch version: 9.2(1)
![image](https://user-images.githubusercontent.com/43453987/188153461-0d0453e2-d717-4416-a1ac-aa3cdf10862a.png)

**Comment by srbharadwaj** [comment]
Thanks. I have identified the issue, will fix it shortly.

**Comment by srbharadwaj** [comment]
@fvandonk Please install the latest version 1.5.1 , it should fix the issue, let me know if you still find problems with the latest one.

**Comment by fvandonk** [comment]
I upgraded  to 1.5.1 and retried the script. It now works as expected. Thanks for the quick fix,

**Comment by srbharadwaj** [comment]
Thanks for the update @fvandonk .
